name: Publish to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dandeduck/weebify-scores:latest
  
  azure:
    runs-on: ubuntu-latest
    steps:    
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: 'Deploy to Azure Container Instances'
        uses: Azure/aci-deploy@v1
        with:
          resource-group: weebify
          dns-name-label: dandeduck/weebify-scores
          image: weebify-scores
          name: weebify-scores
          location: 'west europe'
